# Generated by Django 4.2.2 on 2023-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=50, verbose_name='Имя')),
                ('director', models.CharField(max_length=50, verbose_name='Производитель')),
                ('datastart', models.DateField(max_length=10, verbose_name='Год начала выпуска')),
                ('dataend', models.DateField(max_length=10, verbose_name='Год окончания выпуска')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=50, verbose_name='Email автора')),
                ('avtocar', models.CharField(max_length=50, verbose_name='Автомобиль')),
                ('datacreate', models.DateTimeField(max_length=10, verbose_name='Дата создания')),
                ('comment', models.TextField(max_length=400, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50, verbose_name='Имя')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитль',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
